[package]
authors = ["Ammar Askar <ammar@ammaraskar.com>"]
name = "rusty-bee"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.24.3"
