[package]
name = "rusty-bee-nrf52840"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile-register = "0.2.1"
byte = "0.2.6"
ieee802154 = "0.6"
rusty-bee = { path = "../rusty-bee" }

[build-dependencies]
cbindgen = "0.24.3"
